GET http://localhost:3000/events

###
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
  "name": "Event 100",
  "description": "Event description 100",
  "date": "{{$datetime iso8601}}",
  "price": 100
}

###
@eventId = {{ createEvent.response.body.id }}

###
GET http://localhost:3000/events/{{eventId}}

###
PATCH  http://localhost:3000/events/{{eventId}}
Content-Type: application/json

{
  "name": "The Eras Tour",
  "date": "{{$datetime iso8601}}",
  "description": "Loirinha's show",
  "price": 10000
}

###
DELETE http://localhost:3000/events/{{eventId}}

###
GET http://localhost:3000/events/{{eventId}}/spots

###
# @name createSpot
POST http://localhost:3000/events/{{eventId}}/spots
Content-Type: application/json

{
  "name": "J23"
}

###
@spotId = {{ createSpot.response.body.id }}
@spotName = {{ createSpot.response.body.name }}

###
GET http://localhost:3000/events/{{eventId}}/spots/{{spotId}}

###
PATCH  http://localhost:3000/events/{{eventId}}/spots/{{spotId}}
Content-Type: application/json

{
  "name": "B10"
}

###
DELETE http://localhost:3000/events/{{eventId}}/spots/{{spotId}}

###
POST http://localhost:3000/events/{{eventId}}/reserve
Content-Type: application/json
X-Api-Token: 123

{
  "spots": ["{{ spotName }}"],
  "ticket_kind": "full",
  "email": "email@email.com"
}