GET http://localhost:3000/events

###
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
  "name": "Event 2",
  "description": "Event description 2",
  "date": "{{$datetime iso8601}}",
  "price": 100
}

###
@eventId = {{ createEvent.response.body.id }}

###
GET http://localhost:3000/events/{{eventId}}

###
PATCH  http://localhost:3000/events/{{eventId}}
Content-Type: application/json

{
  "name": "The Eras Tour",
  "date": "{{$datetime iso8601}}",
  "description": "Tinhosa's show",
  "price": 1000000000000000000000
}